version = 1
SPDX-PackageName = "openmcp-project/.github"
SPDX-PackageDownloadLocation = "https://github.com/openmcp-project/.github"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and openMCP contributors and portal contributors."
SPDX-License-Identifier = "Apache-2.0"
